{
  imports = [
    ./avante.nix
    ./basic_plugins.nix
    ./blink.nix
    ./bufferline.nix
    ./colorscheme.nix
    ./conform.nix
    ./extra_plugins.nix
    ./keymaps.nix
    ./lightbulb.nix
    ./lsp.nix
    ./neotest.nix
    ./noice.nix
    ./oil.nix
    ./opts.nix
    ./rust.nix
    ./telescope.nix
    ./treesitter.nix
  ];
}
