{
  imports = [
    ./basic_plugins.nix
    ./blink.nix
    ./bufferline.nix
    ./claude-code.nix
    ./colorscheme.nix
    ./extra_plugins.nix
    ./fzf-lua.nix
    ./keymaps.nix
    ./lightbulb.nix
    ./lsp.nix
    ./markview.nix
    ./neotest.nix
    ./oil.nix
    ./opts.nix
    ./rust.nix
    ./treesitter.nix
  ];
}
